// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1qae20D1rWgKNkGzIpUfMraAxmbhyoc',
    appId: '1:198846245506:web:79b452339d468691a6e29b',
    messagingSenderId: '198846245506',
    projectId: 'lexmachina-law-ai',
    authDomain: 'lexmachina-law-ai.firebaseapp.com',
    storageBucket: 'lexmachina-law-ai.firebasestorage.app',
    measurementId: 'G-G4JNKEKLSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNobImr_jrmYn9nBXNgakU5167_dt_V-4',
    appId: '1:198846245506:android:4a30b4068535480ea6e29b',
    messagingSenderId: '198846245506',
    projectId: 'lexmachina-law-ai',
    storageBucket: 'lexmachina-law-ai.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu1qae20D1rWgKNkGzIpUfMraAxmbhyoc',
    appId: '1:198846245506:web:a0c6a1b86f4bba7ba6e29b',
    messagingSenderId: '198846245506',
    projectId: 'lexmachina-law-ai',
    authDomain: 'lexmachina-law-ai.firebaseapp.com',
    storageBucket: 'lexmachina-law-ai.firebasestorage.app',
    measurementId: 'G-D1F33D5KKR',
  );
}
